# Generated by Django 3.2.5 on 2021-10-25 14:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('puesta_marcha', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=20)),
                ('voltaje', models.CharField(max_length=4)),
                ('amperios', models.CharField(max_length=4)),
                ('numequipo', models.CharField(max_length=20)),
                ('fabricante', models.CharField(max_length=20)),
                ('descripcion', models.TextField(help_text='Ingrese una breve descripción del equipo', max_length=1000)),
                ('serial', models.CharField(help_text='Serial del equipo', max_length=13, verbose_name='Serial')),
                ('edificio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.edificio')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingrese el tipo de equipo:', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MaquinaEstado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID único para este equipo en particular.', primary_key=True, serialize=False)),
                ('estado', models.CharField(blank=True, choices=[('m', 'Maintenance'), ('o', 'On loan'), ('a', 'Available')], default='m', help_text='Disponibilidad del equipo', max_length=1)),
                ('maquina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.maquina')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='maquina',
            name='tipo',
            field=models.ManyToManyField(help_text='Seleccione un tipo de equipo', to='catalog.Tipo'),
        ),
    ]
